global using AutoMapper;
global using JwtIdentity.Common.Auth;
global using JwtIdentity.Common.ViewModels;
global using JwtIdentity.Components;
global using JwtIdentity.Data;
global using JwtIdentity.Model;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using AutomapperProfile = AutoMapper.Profile;
